apiVersion: v1
kind: Namespace
metadata:
  name: entangle
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: entangle
  namespace: entangle
spec:
  chart: entangle
  repo: https://kairos-io.github.io/helm-charts
  version: "@VERSION@"
