apiVersion: v1
kind: Namespace
metadata:
  name: osbuilder
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: osbuilder
  namespace: osbuilder
spec:
  chart: osbuilder
  repo: https://kairos-io.github.io/helm-charts
  version: "@VERSION@"
