apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno
  namespace: kyverno
spec:
  name: kyverno
  chart: kyverno
  repo: https://kyverno.github.io/kyverno/
  valuesContent: |-
    @VALUES@
  version: "@VERSION@"
