name: Lint
on:
 push:
   branches:
     - main
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - name: Run Lint checks
        run: |
          ./earthly.sh +lint
